source "http://gems.ruby-china.org"

gem "autoprefixer-rails"
gem "html-proofer"
gem "jekyll"
gem "jekyll-assets"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jemoji"
gem "mini_magick"
gem "sass"
gem "uglifier"
